In [1]:
import pandas as pd


datos2022 = pd.read_csv("../data/GRD_PUBLICO_EXTERNO_2022.txt", encoding="utf-16", sep="|", engine="python", on_bad_lines="skip")
datos2023 = pd.read_csv("../data/GRD_PUBLICO_2023.txt", encoding="utf-16", sep="|", engine="python", on_bad_lines="skip")
datos2024 = pd.read_csv("../data/GRD_PUBLICO_2024.txt", encoding="latin-1", sep="|", engine="python", on_bad_lines="skip")

In [4]:
# Ver valores nulos
count = (datos2022['CIP_ENCRIPTADO'] == "DESCONOCIDO").sum()
print(count)
count = (datos2023['CIP_ENCRIPTADO'] == "DESCONOCIDO").sum()
print(count)
count = (datos2024['ID_BENEFICIARIO'] == "DESCONOCIDO").sum()
print(count)

2949
1635
1037

In [3]:
display(datos2022.sample(5))
display(datos2023.sample(5))
display(datos2024.sample(5))

,COD_HOSPITAL,CIP_ENCRIPTADO,SEXO,FECHA_NACIMIENTO,ETNIA,PROVINCIA,COMUNA,NACIONALIDAD,PREVISION,SERVICIO_SALUD,...,FECHAPROCEDIMIENTO1,FECHAINTERV1,ESPECIALIDADINTERVENCION,MEDICOALTA_ENCRIPTADO,USOSPABELLON,IR_29301_COD_GRD,IR_29301_PESO,IR_29301_SEVERIDAD,IR_29301_MORTALIDAD,HOSPPROCEDENCIA
388161,112102,96068592,MUJER,2018-07-24,OTRO,TALCA,TALCA,CHILE,FONASA INSTITUCIONAL - (MAI) B,DEL MAULE,...,NaN,2022-07-14,TRAUMATOLOGÍA Y ORTOPEDIA,98438434,1.0,081601,"1,2157",1,1,HOSPITAL DR. CÉSAR GARAVAGNO BUROTTO (TALCA)
176330,115100,69026532,MUJER,1938-11-26,OTRO,CACHAPOAL,RANCAGUA,CHILE,FONASA INSTITUCIONAL - (MAI) B,LIBERTADOR B. O HIGGINS,...,NaN,2022-09-30,TRAUMATOLOGÍA Y ORTOPEDIA,95064923,1.0,081202,"1,4691",2,2,NaN
694599,113100,99226564,HOMBRE,2022-08-14,OTRO,SANTIAGO,SAN MIGUEL,CHILE,FONASA INSTITUCIONAL - (MAI) A,METROPOLITANO SUR,...,NaN,NaN,NaN,98438434,NaN,158173,"0,9864",3,3,NaN
367306,120101,70804244,MUJER,1976-10-17,OTRO,BIO-BIO,QUILLECO,CHILE,FONASA INSTITUCIONAL - (MAI) D,BIOBIO,...,NaN,2022-12-05,OBSTETRICIA Y GINECOLOGÍA,69882233,1.0,131301,"0,6406",1,1,NaN
67264,103100,95894284,MUJER,1965-02-08,OTRO,ANTOFAGASTA,ANTOFAGASTA,COLOMBIA,FONASA INSTITUCIONAL - (MAI) C,ANTOFAGASTA,...,NaN,2022-12-19,OTORRINOLARINGOLOGÍA,88173584,1.0,033100,"0,1017",0,0,NaN

,COD_HOSPITAL,CIP_ENCRIPTADO,SEXO,FECHA_NACIMIENTO,ETNIA,PROVINCIA,COMUNA,NACIONALIDAD,PREVISION,SERVICIO_SALUD,...,FECHAPROCEDIMIENTO1,FECHAINTERV1,ESPECIALIDADINTERVENCION,MEDICOALTA_ENCRIPTADO,USOSPABELLON,IR_29301_COD_GRD,IR_29301_PESO,IR_29301_SEVERIDAD,IR_29301_MORTALIDAD,HOSPPROCEDENCIA
978769,117101,69601183,HOMBRE,1999-11-09,OTRO,CONCEPCION,CORONEL,CHILE,FONASA INSTITUCIONAL - (MAI) B,ÑUBLE,...,NaN,20-02-2023,TRAUMATOLOGÍA Y ORTOPEDIA,69121752,1.0,081203,"2,229",3,2,CLINICA ANDES SALUD CHILLAN
714543,106100,68791571,MUJER,2000-03-19,OTRO,VALPARAISO,VALPARAISO,CHILE,FONASA INSTITUCIONAL - (MAI) A,VALPARAISO SAN ANTONIO,...,NaN,NaN,MATRONAS(ES),85961342,1.0,146121,"0,3109",1,1,NaN
863706,112101,75229231,MUJER,1992-03-19,OTRO,SANTIAGO,LA REINA,CHILE,FONASA INSTITUCIONAL - (MAI) B,METROPOLITANO ORIENTE,...,NaN,17-04-2023,OBSTETRICIA Y GINECOLOGÍA,68846273,1.0,146112,"0,538",2,1,NaN
140206,116105,67226398,HOMBRE,1952-07-06,OTRO,CAUQUENES,CAUQUENES,CHILE,FONASA LIBRE ELECCIÓN (FMLE_B),DEL MAULE,...,NaN,10-02-2023,OTORRINOLARINGOLOGÍA,71736380,1.0,031201,"1,0164",1,1,NaN
573831,119100,78544641,MUJER,1989-08-04,OTRO,CONCEPCION,HUALPÉN,CHILE,FONASA INSTITUCIONAL - (MAI) A,TALCAHUANO,...,NaN,NaN,NaN,71246804,NaN,134161,"0,2951",1,1,NaN

,COD_HOSPITAL,ID_BENEFICIARIO,SEXO,FECHA_NACIMIENTO,ETNIA,PROVINCIA,COMUNA,NACIONALIDAD,PREVISION,SERVICIO_SALUD,...,FECHAPROCEDIMIENTO1,FECHAINTERV1,ESPECIALIDADINTERVENCION,MEDICOALTA_ENCRIPTADO,USOSPABELLON,IR_29301_COD_GRD,IR_29301_PESO,IR_29301_SEVERIDAD,IR_29301_MORTALIDAD,HOSPPROCEDENCIA
404205,118106,72999726,MUJER,1991-09-28,NINGUNO,CONCEPCION,LOTA,CHILE,FONASA INSTITUCIONAL - (MAI) B,CONCEPCIÓN,...,NaN,2024-02-12,OBSTETRICIA Y GINECOLOGÍA,76081256,1.0,132210,"0,9538",0,0,NaN
405993,116105,100603700,HOMBRE,2024-05-15,NINGUNO,TALCA,SAN CLEMENTE,CHILE,FONASA INSTITUCIONAL - (MAI) B,DEL MAULE,...,NaN,NaN,NaN,78912011,NaN,164141,"0,4961",1,1,NaN
146387,111100,79174661,MUJER,2015-04-28,NINGUNO,TALAGANTE,PADRE HURTADO,CHILE,FONASA INSTITUCIONAL - (MAI) B,METROPOLITANO OCCIDENTE,...,NaN,NaN,NaN,71237831,NaN,084131,"0,6176",1,1,NaN
565259,123100,81161069,HOMBRE,1976-09-02,NINGUNO,OSORNO,OSORNO,CHILE,FONASA INSTITUCIONAL - (MAI) D,OSORNO,...,NaN,2024-08-11,CIRUGÍA VASCULAR PERIFÉRICA,87037357,1.0,052170,"0,5791",0,0,NaN
417989,105102,74219032,HOMBRE,1962-09-04,NINGUNO,LIMARI,OVALLE,CHILE,FONASA INSTITUCIONAL - (MAI) C,COQUIMBO,...,NaN,DESCONOCIDA,MÉDICO GENERAL,98439845,5.0,061501,"0,61",1,1,NaN

In [ ]:
datos2024 = datos2024.rename(columns={"ID_BENEFICIARIO": "CIP_ENCRIPTADO"})
data_fechas = [col for col in datos2023.columns if "fecha" in col.lower()]
for x in data_fechas:
    datos2022[f"{x}"] = pd.to_datetime(datos2022[f"{x}"], dayfirst=True, errors="coerce")
    datos2023[f"{x}"] = pd.to_datetime(datos2023[f"{x}"], dayfirst=True, errors="coerce")
    datos2024[f"{x}"] = pd.to_datetime(datos2024[f"{x}"], dayfirst=True, errors="coerce")
cols1 = set(datos2022.columns)
cols2 = set(datos2023.columns)
cols3 = set(datos2024.columns)

diferentes = (cols1 | cols2 | cols3) - (cols1 & cols2 & cols3)

print(diferentes)
print("Solo en df1:", cols1 - cols2 - cols3)
print("Solo en df2:", cols2 - cols1 - cols3)
print("Solo en df3:", cols3 - cols1 - cols2)

print("df1 vs df2:", cols1.symmetric_difference(cols2))
print("df1 vs df3:", cols1.symmetric_difference(cols3))
print("df2 vs df3:", cols2.symmetric_difference(cols3))

C:\Users\nicol\AppData\Local\Temp\ipykernel_1972\2900051569.py:4: UserWarning: Parsing dates in %Y-%m-%d format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  datos2022[f"{x}"] = pd.to_datetime(datos2023[f"{x}"], dayfirst=True, errors="coerce")
C:\Users\nicol\AppData\Local\Temp\ipykernel_1972\2900051569.py:5: UserWarning: Parsing dates in %Y-%m-%d format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  datos2023[f"{x}"] = pd.to_datetime(datos2023[f"{x}"], dayfirst=True, errors="coerce")

set()
Solo en df1: set()
Solo en df2: set()
Solo en df3: set()
df1 vs df2: set()
df1 vs df3: set()
df2 vs df3: set()

In [5]:
def comparar_columnas(*dfs):
    columnas = set()
    for df in dfs:
        columnas.update(df.columns)

    resultado = {}

    for i, df in enumerate(dfs):
        ejemplos = []
        for col in columnas:
            if col in df.columns:
                serie = df[col].dropna()
                valor = serie.iloc[0] if not serie.empty else None
                ejemplos.append(f"{valor} ({df[col].dtype})")
            else:
                ejemplos.append("NO EXISTE")
        resultado[f"df{i+1}"] = ejemplos

    return pd.DataFrame(resultado, index=list(columnas))

muestra = comparar_columnas(datos2022, datos2023, datos2024)
print(muestra)

                                             df1  \
SERVICIOINGRESO           CIRUGÍA INFANTIL (str)
PROCEDIMIENTO11                  99.19 (float64)
DIAGNOSTICO1                         Q03.9 (str)
DIAGNOSTICO12                        R41.0 (str)
DIAGNOSTICO2                           H55 (str)
...                                          ...
DIAGNOSTICO14                        N39.0 (str)
DIAGNOSTICO4                           R13 (str)
MEDICOINTERV1_ENCRIPTADO    72370257.0 (float64)
PROCEDIMIENTO24                  86.28 (float64)
DIAGNOSTICO21                        I72.2 (str)

                                                      df2  \
SERVICIOINGRESO           TRAUMATOLOGÍA Y ORTOPEDIA (str)
PROCEDIMIENTO11                               89.65 (str)
DIAGNOSTICO1                                  K35.3 (str)
DIAGNOSTICO12                                   R12 (str)
DIAGNOSTICO2                                  Z35.3 (str)
...                                                   ...
DIAGNOSTICO14                                 Z92.4 (str)
DIAGNOSTICO4                                  Z37.0 (str)
MEDICOINTERV1_ENCRIPTADO             71695588.0 (float64)
PROCEDIMIENTO24                           99.21 (float64)
DIAGNOSTICO21                                 Z90.8 (str)

                                                                        df3
SERVICIOINGRESO           UNIDAD DE RECUPERACIÓN DE PABELLONES (CENTRAL ...
PROCEDIMIENTO11                                             99.23 (float64)
DIAGNOSTICO1                                                    H26.9 (str)
DIAGNOSTICO12                                                   N28.1 (str)
DIAGNOSTICO2                                                    R57.2 (str)
...                                                                     ...
DIAGNOSTICO14                                                   E80.6 (str)
DIAGNOSTICO4                                                    A41.0 (str)
MEDICOINTERV1_ENCRIPTADO                               71043147.0 (float64)
PROCEDIMIENTO24                                             91.39 (float64)
DIAGNOSTICO21                                                   E03.9 (str)

[129 rows x 3 columns]