In [1]:
import pandas as pd

In [2]:
cols = ['FECHA_INGRESO', 'FECHAALTA', "FECHA_NACIMIENTO"]
datos2022 = pd.read_csv("../data/GRD_PUBLICO_EXTERNO_2022.txt", encoding="utf-16", sep="|", engine="python", on_bad_lines="skip", usecols=cols)
datos2023 = pd.read_csv("../data/GRD_PUBLICO_2023.txt", encoding="utf-16", sep="|", engine="python", on_bad_lines="skip", usecols=cols)
datos2024 = pd.read_csv("../data/GRD_PUBLICO_2024.txt", encoding="latin-1", sep="|", engine="python", on_bad_lines="skip", usecols=cols)

In [3]:
datos2022["FECHA_INGRESO"] = pd.to_datetime(datos2022["FECHA_INGRESO"])
datos2022["FECHAALTA"] = pd.to_datetime(datos2022["FECHAALTA"])
datos2022["FECHA_NACIMIENTO"] = pd.to_datetime(datos2022["FECHA_NACIMIENTO"], errors="coerce")

datos2022["DIAS"] = (datos2022["FECHAALTA"] - datos2022["FECHA_INGRESO"]).dt.days
datos2022["EDAD"] = (
    (datos2022["FECHA_INGRESO"] - datos2022["FECHA_NACIMIENTO"])
    .dt.days // 365
)
casos_raros = datos2022[(datos2022["EDAD"] == 0) & (datos2022["DIAS"] > 100)]
print(len(casos_raros))

# =========================
# 2023 (dayfirst=True)
# =========================
datos2023["FECHA_INGRESO"] = pd.to_datetime(datos2023["FECHA_INGRESO"], dayfirst=True)
datos2023["FECHAALTA"] = pd.to_datetime(datos2023["FECHAALTA"], dayfirst=True)
datos2023["FECHA_NACIMIENTO"] = pd.to_datetime(datos2023["FECHA_NACIMIENTO"], errors="coerce")

datos2023["DIAS"] = (datos2023["FECHAALTA"] - datos2023["FECHA_INGRESO"]).dt.days
datos2023["EDAD"] = (
    (datos2023["FECHA_INGRESO"] - datos2023["FECHA_NACIMIENTO"])
    .dt.days // 365
)
casos_raros = datos2023[(datos2023["EDAD"] == 0) & (datos2023["DIAS"] > 100)]
print(len(casos_raros))
# =========================
# 2024 (con "DESCONOCIDO")
# =========================
datos2024["FECHA_INGRESO"] = pd.to_datetime(datos2024["FECHA_INGRESO"], dayfirst=True, errors="coerce")
datos2024["FECHAALTA"] = pd.to_datetime(datos2024["FECHAALTA"], dayfirst=True, errors="coerce")
datos2024["FECHA_NACIMIENTO"] = pd.to_datetime(datos2024["FECHA_NACIMIENTO"], errors="coerce")

datos2024 = datos2024.dropna(subset=["FECHA_INGRESO", "FECHAALTA"])

datos2024["DIAS"] = (datos2024["FECHAALTA"] - datos2024["FECHA_INGRESO"]).dt.days
datos2024["EDAD"] = (
    (datos2024["FECHA_INGRESO"] - datos2024["FECHA_NACIMIENTO"])
    .dt.days // 365
)
casos_raros = datos2024[(datos2024["EDAD"] == 0) & (datos2024["DIAS"] > 100)]
print(len(casos_raros))

# Contar desconocidos (ahora son NaT)
desconocidos_ingreso_2024 = datos2024["FECHA_INGRESO"].isna().sum()
desconocidos_alta_2024 = datos2024["FECHAALTA"].isna().sum()

421
434

C:\Users\nicol\AppData\Local\Temp\ipykernel_5836\2079098329.py:30: UserWarning: Parsing dates in %Y-%m-%d format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  datos2024["FECHA_INGRESO"] = pd.to_datetime(datos2024["FECHA_INGRESO"], dayfirst=True, errors="coerce")
C:\Users\nicol\AppData\Local\Temp\ipykernel_5836\2079098329.py:31: UserWarning: Parsing dates in %Y-%m-%d format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  datos2024["FECHAALTA"] = pd.to_datetime(datos2024["FECHAALTA"], dayfirst=True, errors="coerce")

465

In [4]:
fecha_corte = pd.Timestamp("2022-01-01")

datos2022 = datos2022[datos2022["FECHA_INGRESO"] >= fecha_corte]
datos2023 = datos2023[datos2023["FECHA_INGRESO"] >= fecha_corte]
datos2024 = datos2024[datos2024["FECHA_INGRESO"] >= fecha_corte]

In [5]:
dias = 200
# 2022
mas_100_2022 = (datos2022["DIAS"] > dias).sum()
df_mas_100_2022 = datos2022[datos2022["DIAS"] > dias]

# 2023
mas_100_2023 = (datos2023["DIAS"] > dias).sum()
df_mas_100_2023 = datos2023[datos2023["DIAS"] > dias]

# 2024
mas_100_2024 = (datos2024["DIAS"] > dias).sum()
df_mas_100_2024 = datos2024[datos2024["DIAS"] > dias]

print("2022:", mas_100_2022)

print("2023:", mas_100_2023)

print("2024:", mas_100_2024)

2022: 107
2023: 434
2024: 416

In [8]:
display(df_mas_100_2022[df_mas_100_2022["DIAS"] > 500])
display(df_mas_100_2023[df_mas_100_2023["DIAS"] > 500])
display(df_mas_100_2024[df_mas_100_2024["DIAS"] > 500])

Empty DataFrame
Columns: [FECHA_NACIMIENTO, FECHA_INGRESO, FECHAALTA, DIAS, EDAD]
Index: []

       FECHA_NACIMIENTO FECHA_INGRESO  FECHAALTA  DIAS  EDAD
76805        2000-08-01    2022-01-17 2023-09-01   592  21.0
126900       1953-12-05    2022-02-26 2023-11-19   631  68.0
140621       2022-02-05    2022-02-05 2023-12-04   667   0.0
198781       1948-11-16    2022-04-18 2023-09-05   505  73.0
252235       2001-05-31    2022-02-08 2023-06-29   506  20.0
256554       1944-01-21    2022-03-16 2023-08-21   523  78.0
341840       1954-02-04    2022-03-05 2023-08-25   538  68.0
423813       2021-09-30    2022-07-15 2023-12-22   525   0.0
484010       1953-12-06    2022-06-27 2023-11-24   515  68.0
614758       1971-06-23    2022-01-28 2023-07-27   545  50.0
769170       1948-04-08    2022-07-05 2023-12-28   541  74.0
790921       1948-01-23    2022-03-11 2023-08-04   511  74.0
828658       2022-04-11    2022-06-20 2023-12-09   537   0.0
832950       1966-09-04    2022-03-08 2023-09-01   542  55.0
835050       1967-06-25    2022-04-12 2023-09-15   521  54.0
864158       2021-10-25    2022-04-27 2023-09-20   511   0.0
864906       2021-10-13    2022-07-05 2023-11-23   506   0.0
865007       2022-04-04    2022-04-04 2023-08-21   504   0.0
951917       1989-09-03    2022-01-13 2023-12-10   696  32.0
964244       2021-06-24    2022-05-16 2023-11-16   549   0.0

        FECHA_NACIMIENTO FECHA_INGRESO  FECHAALTA  DIAS  EDAD
107557        1992-12-03    2023-05-23 2024-11-25   552  30.0
383144        2022-06-01    2023-01-13 2024-06-06   510   0.0
466434        2023-01-01    2023-01-01 2024-10-23   661   0.0
476460        2023-02-22    2023-02-23 2024-10-09   594   0.0
523160        1951-01-24    2023-03-20 2024-12-24   645  72.0
527164        2023-03-02    2023-04-25 2024-10-14   538   0.0
588143        1961-12-19    2023-05-13 2024-11-06   543  61.0
755814        2023-05-17    2023-05-17 2024-12-16   579   0.0
760384        2021-03-29    2023-06-08 2024-10-23   503   2.0
776799        1998-07-10    2023-03-07 2024-09-03   546  24.0
827553        2012-06-28    2023-07-12 2024-11-26   503  11.0
833226        1959-01-27    2023-02-10 2024-09-09   577  64.0
850922        1969-09-09    2023-01-06 2024-09-15   618  53.0
895392        1970-02-08    2023-03-01 2024-11-20   630  53.0
956003        1950-09-29    2023-04-24 2024-09-08   503  72.0
1041827       1968-12-16    2023-08-10 2024-12-24   502  54.0
1085632       1957-06-01    2023-01-04 2024-07-12   555  65.0